### ISSUE TITLE
To Do's to complete this project

### ISSUE THREAD

**Issue by hudspace** [hudspace/airbusnotes#1]
## Task List:

- [ ] Write javascript to make mobile dropdown menu links (two menus, main nav page and NTSB links menu) functional

- [ ] Write javascript to make the Memory Items and Limitations quiz work (score answers and return results to user

- [ ] Write javascript implementing photo gallery with light box functionality

- [ ] Write Best Practices page content
